{% set name = "uritools" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee06a182a9c849464ce9d5fa917539aacc8edd2a4924d1b7aabeeecabcae3bc2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - uritools

  commands:
    - python -m unittest discover

  source_files:
    - tests

about:
  home: https://github.com/tkem/uritools/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: RFC 3986 compliant, Unicode-aware, scheme-agnostic replacement for urlparse
  dev_url: https://github.com/tkem/uritools/
  doc_url: http://pythonhosted.org/uritools/

extra:
  recipe-maintainers:
    - ltalirz
