{% set name = "uritools" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d671c3b8ca230a5d47efa5f8a693f3d01531f38f4f523170299be734cc9851b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - uritools
  commands:
    - pip check
    - python -m unittest discover
  source_files:
    - tests
  requires:
    - python {{ python_min }}
    - pip


about:
  home: https://github.com/tkem/uritools/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: RFC 3986 compliant, Unicode-aware, scheme-agnostic replacement for urlparse
  dev_url: https://github.com/tkem/uritools/
  doc_url: http://pythonhosted.org/uritools/

extra:
  recipe-maintainers:
    - ltalirz
