appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Y763Mgfpee+A9NL3eYbn1zEisHS2AJABtSyG2Cc2UTbPIAmy1Nmt6rpJiBwMLPTaR5my9kFJGVGT19Y5gTMUfjLN5mYq9X+Gykmwi6XwmgDy4CFSu+LvmgoYoaIzdh8yCv4eD7l30x015juAf3HDZQAM0qq/ktA3M5ZKgq+exBj6CkcX4XyTy+5sZwvb2q+p6Lr6prmm1uQmrabQFhGHHc3ZvvTW3Nip1FAJeuNn215gjzoGJR3pHUBJsI+r3/k0XK+ebF+49N1JmkWGr/CItLNyNXYCVr3OKopThqRLwpFDHVHCmOJbmjbp+MKMvTT43MMIG5dg1M60gDvf0fEa1ggiQumFS6nEwZ+nZdIHvv1XdS7n6dRXfwRasGzrHIl07bK9pb2IGtxEtzGfCCs2M9P6OowkRoMFox1nn3zrNK34ngojSLXmLyuA2fFxJEg/5WSJWRvP6Ye78r6TUw4LcZQ20pD2EsqoE0Q0cKmQHbGpZFDtQUw15Np+bG9HO5HzUvLggGc9khS4/Gh8LwC3ZjiiaJ84miNYuWiv/p2wRserO15fP36E36yQXcHF1t2lp+CXLx9vGWyev5OAisvKBFs8rWotoJ9z42tOPp/+yjtOvpEHDChrCxGvNqgrt3o/M3ftCEW8Wo8vOGMMmRfvCVAbjg62ZvPr9JcQ64vM0CE=}
